[package]
name = "oteryn-world-directory"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.oteryn]
category = "world-directory"

[dependencies]
oteryn-account-session = { version = "=0.1.0", path = "../account-session" }

[lints]
workspace = true
