[package]
name = "oteryn-platform"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.oteryn]
category = "platform"

[dependencies]
oteryn-account-session = { version = "=0.1.0", path = "../account-session" }
oteryn-foundation = { version = "=0.1.0", path = "../foundation" }
oteryn-game-session = { version = "=0.1.0", path = "../game-session" }
oteryn-world-directory = { version = "=0.1.0", path = "../world-directory" }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json.workspace = true
time = { version = "=0.3.54", default-features = false, features = ["parsing", "std"] }
ureq = { version = "=3.3.0", default-features = false, features = ["native-tls-no-default"] }
url = "=2.5.8"

[lints]
workspace = true
