name: Reusable Docker Build

on:
  workflow_call:

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Image Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false

      - name: Convert repository name to lowercase
        id: repo_lower
        shell: bash
        run: echo "value=${REPO,,}" >> "${GITHUB_OUTPUT}"
        env:
          REPO: ${{ github.repository }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c  # v4.2.0

      - name: Build and export without repository credentials
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a  # v7.3.0
        with:
          context: .
          file: Dockerfile
          push: false
          outputs: type=local,dest=artifacts/docker-rootfs
          tags: ghcr.io/${{ steps.repo_lower.outputs.value }}:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload docker artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: docker-otclient
          path: artifacts/docker-rootfs/otclient/
          retention-days: 7
